### ISSUE TITLE
重构 Makefile.am

### ISSUE THREAD

**Issue by RyanBernX** [wangheyu/AFEPack#2]
源码中只有部分的目录里有 Makefile.am，其他目录则是直接手写 Makefile，而不是用 configure 生成。是否考虑统一一下 Makefile 的生成方式？

**Comment by wangheyu** [comment]
这个...等稳定下来可以搞一下吧？

**Comment by RyanBernX** [comment]
目前我是有这样的计划，想法是最终把 autoconf 和 automake 整合到一起，尽量和标准库做的一致一些。
我还在看相关文档，有时间了可以再发一个 pull request。

**Comment by wangheyu** [comment]
李若老师修改了configure.in，目前似乎暂时可以不用手工修改安装脚本，我在Ubuntu下测试过，其他平台不知道有什么问题，如果有人尝试过有问题可以提出。
