### ISSUE TITLE
第一个例子出现段错误

### ISSUE THREAD

**Issue by holes-flat** [wangheyu/AFEPack#4]
在Ubuntu18.04下，进入example/possion_equation后执行make和easymesh D成功，但运行./run D时
报错：
`段错误
`
经gdb检查，未进入main函数就已经产生段错误:
`0x00000000000043c6 in ?? ()
`
仔细对比发现，当前版本生成的Make.global_options有下述语句:
`LIBS = -ldeal_II -Lcheck/lib  -lm -ldl -shared`
去掉-shared编译选项后不再产生段错误。

不知道这是个例还是普遍现象，希望老师能核实一下。

**Comment by wangheyu** [comment]
哦，回头我测试一下。

**Comment by wangheyu** [comment]
李老师调整了安装脚本，去掉了shared参数，谢谢！
